name: ci
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Lint/Format/Type
        run: |
          ruff check .
          ruff format --check .
          black --check .
          mypy app || true
      - name: Tests
        run: pytest -q || true
      - name: Build Docker
        run: docker build -f docker/Dockerfile -t tracker2:ci .